### PR TITLE
Fix `hitSlop` on Gesture Handler buttons

### PR DESCRIPTION
**Pull request by j-piasecki**
## Description

This PR does two things:
- (iOS) sets `hitTestEdgeInsets` on `RNGestureHandlerButton` when Fabric is enabled
- (Android) sets `clipChildren` to `false` on `ButtonViewGroup`

The second change makes the button behavior consistent with iOS where its content isn't clipped. It also fixes https://github.com/software-mansion/react-native-gesture-handler/issues/1242 because of [this line](https://github.com/software-mansion/react-native-gesture-handler/blob/1217039146ddcae6796820b5ecf19d1ff51af837/android/lib/src/main/java/com/swmansion/gesturehandler/GestureHandlerOrchestrator.kt#L449), which tried to extract handlers from view when it's not clipping children.

## Test plan

Tested on the Example app.

### CODE REVIEW

**Comment by j-piasecki** [comment]
@hirbod It should be possible already, because the [`hitSlop` property is transformed when it's not an object](https://github.com/software-mansion/react-native-gesture-handler/blob/b9904f69d225b9a40607795ff4c3fb1575f009b9/src/handlers/gestureHandlerCommon.ts#L156-L158). I tried it on a simple touchable and it worked fine, although the types seem to be wrong, I'll look into it.

**Comment by lightrow** [comment]
can this please be looked at? This is a major annoyance

**Comment by magrinj** [comment]
@j-piasecki Are you able to get this merged soon ? I'm facing the same issue on my side too mostly on Android devices, it's really annoying and frustrating for the users

**Review by m-bert — APPROVED** [review]

**Comment by DenisDov** [comment]
seems not to be fixed on Android

**Pull request merged**
