### PR TITLE
add hooks for swipe start/end

### LINKED ISSUE #1101: add hook for `isDragging` to Swipeable
right now its possible to tell when drag ends (`onSwipeableWillClose`) but there is no way to attach functionality to when dragging starts as far as I can tell. `onSwipeableWillOpen` is only called when opened programmatically, not when the user starts to drag the component

### PR DESCRIPTION
**Pull request by chrisdrackett**
closes #1101

### CODE REVIEW

**Comment by MoOx** [comment]
Would be nice to agree on something as this is a trivial change that is pending for a while. Need any help somehow?

**Comment by pribeh** [comment]
Bump. Tested here and works fine.

**Comment by jakub-gonet** [comment]
I'd say this can be now achieved by #999 so I'll close this one.

Thanks for your contribution!

**Comment by MoOx** [comment]
@jakub-gonet wait noooo. #999 only works for  Drawer while this one is for Swipeable component.

**Comment by jakub-gonet** [comment]
Ohhhhh.

**Comment by MoOx** [comment]
@jakub-gonet what about merging it now? 😅

**Comment by jakub-gonet** [comment]
I think we should allow `onSwipeableWillOpen` to be fired on touch dragging instead of only when opening programmatically if RN does this (I haven't checked that yet). For me adding yet another lifecycle method isn't ideal.

> @jakub-gonet what about merging it now? 😅

This PR lacks a docs and types update so can't right now, but I'd want to discuss ^ first.

**Comment by jakub-gonet** [comment]
Tagging for visibility: @chrisdrackett, @MoOx 

Per [my comment in #935](https://github.com/software-mansion/react-native-gesture-handler/issues/935#issuecomment-733090839) I think this PR should be closed or changed to `onDrag` or a similar method. I'm open for discussion though.

(We're in process of merging PRs, so I'll close this one if there will be no activity for a week – nothing permanent, it can be always reopened if you want to work on this one)

**Comment by chrisdrackett** [comment]
I don't have a strong option on what these props are called myself.

We moved to just rolling our own swappable in July as there wasn't activity on this issue so I don't really have skin in the game for this PR anymore.

**Comment by jakub-gonet** [comment]
All right, thanks for responding. I'll close this one for now – this is a small change codewise but requires us to support two new API methods for Swipeable. It can be reopened in the future after we decide what we should do with Swipeable/Drawer APIs.

Thanks for your contribution anyway, really appreciated.

**Pull request closed without merging**
