### PR TITLE
Expand Jest mocks

### PR DESCRIPTION
**Pull request by TheWirv**
## Description

I have noticed that the mock was missing various components, which is why, up until now, I had to build my own mock that was building upon the one that was provided by RNGH. Now, that my tests broke because the path to the mock changed (to `src/`), I thought, why not add those components via PR instead of just "filing a complaint" via an issue.

### CODE REVIEW

**Review by jakub-gonet — COMMENTED** [review]
Thanks. We recently introduced Bob so `__mocks__/` dirs are ignored when packaging. I think we need to extract mocks to the different file and provide them in `jestSetup.js`

**Comment by TheWirv** [comment]
That makes sense. What about just having a `mock.ts` at root level? The user then can integrate however they want.

**Comment by jakub-gonet** [comment]
We have jestSetup.js which has a similar function:
https://github.com/software-mansion/react-native-gesture-handler/blob/master/jestSetup.js

**Comment by jakub-gonet** [comment]
I recently refactored our mocks so after moving your changes to [mocks.ts](https://github.com/software-mansion/react-native-gesture-handler/blob/master/src/mocks.ts) it should be alright to merge.

**Comment by TheWirv** [comment]
@jakub-gonet Sorry for letting you wait so long, but now I finally merged the prior changes into the new mock file. Good work on the whole TS rewrite so far!

**Review by jakub-gonet — APPROVED** [review]
Looks alright, sorry for the delay.

**Pull request merged**
