### PR TITLE
fix: move Swipeable and DrawerLayout type definition

### PR DESCRIPTION
**Pull request by Naturalclar**
Trying to use `Swipeable` with TypeScript leads to an error, since type for `Swipeable` inside `react-native-gesture-handler.d.ts` is not recognized when importing from `react-native-gesture-handler/Swipeable` as shown in the error below.

Screen Shot 2020-02-10 at 2 32 03 AM

Moved type definition of `Swipeable` to `Swipeable.d.ts` and confirmed that error will disappear.

Also, there was a typo in type for GestureHandlerRootView, so I made a fix for that as well.

### CODE REVIEW

**Comment by sintylapse** [comment]
It would be nice if it work with any exported module, like `Gestures` of `State`

**Comment by osdnk** [comment]
@WoLewicki @jakub-gonet Can you verify and merge it? It's good I believe

**Comment by sperezm97** [comment]
Any updates since the last comment ?

**Comment by tymrl** [comment]
I'm running into this too - any updates?

**Comment by jakub-gonet** [comment]
I can merge it if you guys can verify it fixes your problem, seems pretty straightforward fix

**Comment by jakub-gonet** [comment]
Retriggering checks.

**Comment by slushman** [comment]
Can someone take a look at this? Looks like all tests are passing.

**Comment by jkadamczyk** [comment]
Hey! I tried it and I can happily say, it seems to be working fine.
Good job on that PR and sorry it took so long to get to it. Have a great day!

**Pull request merged**
