### PR TITLE
Bump FabricExample to React Native 0.70.0-rc.4

### PR DESCRIPTION
**Pull request by j-piasecki**
## Description

This PR updates version of React native used by the FabricExample app to 0.70.0-rc-4 and replaces NDK with CMake.

## Test plan

Run the FabricExample app

### CODE REVIEW

**Comment by tomekzaw** [comment]
Zrzut ekranu 2022-08-17 o 12 40 43

**Comment by tomekzaw** [comment]
without (228K) vs. with `ANDROID_STL=c++_shared` (36K):

Zrzut ekranu 2022-08-18 o 14 18 36

**Comment by leotm** [comment]
[`software-mansion/react-native-gesture-handler#9a4bef2c0602c6cb8a95049725277c53f18b7569`](https://github.com/leotm/react-native-template-new-architecture/pull/885/commits/63e072f331b0b6717f5f75c16352a0e62f3dbc9c) fixed the Android CI issue for me btw

**Comment by tomekzaw** [comment]
Hey @leotm!

> [software-mansion/react-native-gesture-handler#9a4bef2c0602c6cb8a95049725277c53f18b7569](https://github.com/leotm/react-native-template-new-architecture/pull/885/commits/63e072f331b0b6717f5f75c16352a0e62f3dbc9c) fixed the Android CI issue for me btw

What RN version are you on?

> any ideas on [pod install'ing](https://github.com/leotm/react-native-template-new-architecture/runs/7916916040?check_suite_focus=true) after that 🤔

This is a bug in RNGH which is fixed by #2173.

**Comment by tomekzaw** [comment]
TODO:
* bump RNSafeAreaContext to 4.3.3

**Comment by leotm** [comment]
hey @tomekzaw! great i'll try that commit or later to fix the `pod install`, on 0.70.0-rc.3

**Comment by leotm** [comment]
> [`software-mansion/react-native-gesture-handler#9a4bef2c0602c6cb8a95049725277c53f18b7569`](https://github.com/leotm/react-native-template-new-architecture/pull/885/commits/63e072f331b0b6717f5f75c16352a0e62f3dbc9c) fixed the Android CI issue for me btw

if i'm right updating this PR to be up-to-date with `main` should fix the remaining FabricExample failing Test Android build, but could be wrong 😆

**Comment by tomekzaw** [comment]
> if i'm right updating this PR to be up-to-date with main should fix the remaining FabricExample failing Test Android build, but could be wrong 😆

The CI in this PR fails due to `libfb.so` missing when compiling RNScreens and RNSafeAreaContext. I've added an additional step to build this shared library before building the app that hopefully will fix the CI. This problem will be eliminated once RNScreens and RNSafeAreaContext adopt the new autolinking mechanism introduced in 0.70.0-rc.3

**Review by tomekzaw — APPROVED** [review]
:shipit:

**Pull request merged**
